import assert from 'node:assert/strict';
import { fetchFootball } from '../lib/providers/espn.ts';
const base = process.env.SKEDY_URL || 'http://localhost:3000';
const page = await fetch(base);
assert.equal(page.status, 200);
const html = await page.text();
assert.match(html, /Your watchlist/);
assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/);
assert.equal((await fetch(base + '/api/schedule?sport=invalid')).status, 400);
assert.equal((await fetch(base + '/api/schedule?from=2026-99-99')).status, 400);
assert.equal((await fetch(base + '/api/sync', { method: 'POST', headers: { Origin: 'https://unrelated.example' } })).status, 403);
const postFootball = body => fetch(base + '/api/football', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
assert.equal((await postFootball({ action: 'save', ticket: 'invalid', events: [] })).status, 409);
const claimResponse = await postFootball({ action: 'claim', force: true });
assert.equal(claimResponse.status, 200);
const claim = await claimResponse.json();
if (claim.claimed) {
  const football = await fetchFootball();
  const saved = await postFootball({ action: 'save', ticket: claim.ticket, events: football.events, standings: football.standings, warning: football.context?.warning });
  assert.equal(saved.status, 200, await saved.text());
  assert.equal((await postFootball({ action: 'save', ticket: claim.ticket, events: football.events })).status, 409, 'A saved refresh cannot be replayed');
}
const response = await fetch(base + '/api/sync?force=1', { method: 'POST', signal: AbortSignal.timeout(180000) });
assert.equal(response.status, 200);
const data = await response.json();
console.log(JSON.stringify({ totalEvents: data.events.length, sources: data.sources, trophy: data.trophy, bySport: Object.fromEntries(['football', 'f1', 'valorant', 'cs2'].map(s => [s, data.events.filter(e => e.sport === s).length])), sampleCs: data.events.filter(e => e.sport === 'cs2').slice(-5).map(e => ({ id: e.id, title: e.title, competition: e.competition, stage: e.stage })), sampleVct: data.events.filter(e => e.sport === 'valorant').slice(0, 2).map(e => ({ title: e.title, competition: e.competition })) }, null, 2));
assert.ok(data.events.some(e => e.category === 'spurs'), 'Spurs fixtures should be available');
assert.ok(data.events.some(e => e.sport === 'f1'), 'F1 sessions should be available');
assert.equal(new Set(data.events.map(e => e.id)).size, data.events.length);
const filtered = await (await fetch(base + '/api/schedule?sport=f1&from=2026-09-10&to=2026-10-10')).json();
assert.ok(filtered.events.every(e => e.sport === 'f1'));
console.log('HTTP and feed smoke checks passed.');
